name: Update Code on Pull Request Merge

on:
  pull_request:
    types:
      - closed
 jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Python Code
        run: |
          # قم بكتابة الأمر الذي سيقوم بتحديث ملف البايثون
          # على سبيل المثال: إضافة قائمة التشغيل إلى ملف البايثون
          echo "playlist = ['channel1', 'channel2']" > path/to/python/generate_playlist.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Python code with new playlist"
          git push

